version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"
  jobs:
    pre_build:
      - touch content/built-in-wheels.txt
      - jupyter lite build --contents content --output-dir dist --pyodide https://github.com/pyodide/pyodide/releases/download/0.24.1/pyodide-0.24.1.tar.bz2
      - cp ./.cache/pyodide/pyodide/pyodide/*.whl ./dist/static/pyodide
      - cp ./wheels/*.whl ./dist/static/pyodide
      - for file in ./dist/static/pyodide/*.whl; do basename "$file"; done | tr -cd '\11\12\15\40-\176' > ./dist/files/built-in-wheels.txt
      - find ./dist -type f -name "*.whl" -exec bash -c "mv '$0' '${0%.whl}.whl.zip'" {} \;
      - cp ./modified/service-worker.js ./dist
      - grep -rl --exclude='*.whl.zip' '.whl' ./dist
    post_build:
      - cp ./modified/service-worker.js ./dist
      - grep -rl --exclude='*.whl.zip' '.whl' ./dist

conda:
  environment: docs/environment.yml

sphinx:
   configuration: docs/conf.py
