name: pyodide-offline
channels:
- conda-forge
dependencies:
- build
- python==3.11
- mamba
- pydata-sphinx-theme
- myst-parser
- jupyterlab>=4.0,<5.0
- nodejs=18
- jupyterlite>=0.2.2,<0.3
- notebook>=7.0.0,<8.0.0
- jupyterlite-pyodide-kernel
- ipywidgets>=8.1.1,<9
- ipyevents>=2.0.1
- ipympl>=0.8.2
- ipycanvas>=0.9.1
- ipyleaflet
- plotly>=5,<6
- bqplot
- pip
- pip:
  - jupyterlite-sphinx
