name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install the dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Build the JupyterLite site
        run: |
          # cp README.md content
          touch content/built-in-wheels.txt
          
          # mkdir ./dist
          # mkdir ./dist/static
          # mkdir ./dist/static/pyodide
          # cp ./wheels/* ./dist/static/pyodide
          
          # cp ./.cache/pyodide/pyodide/pyodide/*.whl ./dist/static/pyodide
          
          jupyter lite build --contents content --output-dir dist --pyodide https://github.com/pyodide/pyodide/releases/download/0.25.0/pyodide-0.25.0.tar.bz2
          cp -n ./wheels/* ./dist/static/pyodide

          ## cp ./modified/all.json ./dist/extensions/@jupyterlite/pyodide-kernel-extension/static/pypi/all.json
          for file in ./dist/static/pyodide/*.whl; do basename "$file"; done | tr -cd '\11\12\15\40-\176' > ./dist/files/built-in-wheels.txt
          # find ./dist -type f -name "*.whl" -exec sh -c 'mv "$1" "./dist/static/pyodide/${1%.whl}.whl.zip"' _ {} \;
          find ./dist -type f -name "*.whl" -print0 | xargs -0 -I{} sh -c 'mv "{}" "./dist/static/pyodide/$(basename "{}" .whl).whl.zip"'

          cp ./modified/service-worker.js ./dist
          grep -rl --exclude='*.whl.zip' '.whl' ./dist
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
